<?php

namespace ContainerKgva9te;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecetteApiControllergetRecetteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nUGD5oq.App\Controller\API\RecetteApiController::getRecette()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nUGD5oq.App\\Controller\\API\\RecetteApiController::getRecette()'] = ($container->privates['.service_locator.nUGD5oq'] ?? $container->load('get_ServiceLocator_NUGD5oqService'))->withContext('App\\Controller\\API\\RecetteApiController::getRecette()', $container);
    }
}
