<?php

namespace Container4dDYsSm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Cpy9hs6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cpy9hs6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cpy9hs6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\API\\AdminApiController::create' => ['privates', '.service_locator.egipcEH.App\\Controller\\API\\AdminApiController::create()', 'getAdminApiControllercreateService', true],
            'App\\Controller\\API\\AdminApiController::findById' => ['privates', '.service_locator.2ath_dA.App\\Controller\\API\\AdminApiController::findById()', 'getAdminApiControllerfindByIdService', true],
            'App\\Controller\\API\\AdminApiController::findByAll' => ['privates', '.service_locator.2ath_dA.App\\Controller\\API\\AdminApiController::findByAll()', 'getAdminApiControllerfindByAllService', true],
            'App\\Controller\\API\\AdminApiController::login' => ['privates', '.service_locator.6nIdJea.App\\Controller\\API\\AdminApiController::login()', 'getAdminApiControllerloginService', true],
            'App\\Controller\\API\\ClientApiController::create' => ['privates', '.service_locator.egipcEH.App\\Controller\\API\\ClientApiController::create()', 'getClientApiControllercreateService', true],
            'App\\Controller\\API\\ClientApiController::findById' => ['privates', '.service_locator.mjCVlfO.App\\Controller\\API\\ClientApiController::findById()', 'getClientApiControllerfindByIdService', true],
            'App\\Controller\\API\\ClientApiController::findByAll' => ['privates', '.service_locator.mjCVlfO.App\\Controller\\API\\ClientApiController::findByAll()', 'getClientApiControllerfindByAllService', true],
            'App\\Controller\\API\\ClientApiController::listClients' => ['privates', '.service_locator.zroWs1n.App\\Controller\\API\\ClientApiController::listClients()', 'getClientApiControllerlistClientsService', true],
            'App\\Controller\\API\\ClientApiController::login' => ['privates', '.service_locator.qvGhemt.App\\Controller\\API\\ClientApiController::login()', 'getClientApiControllerloginService', true],
            'App\\Controller\\API\\CommandeController::getStatistiques' => ['privates', '.service_locator.75P59IX.App\\Controller\\API\\CommandeController::getStatistiques()', 'getCommandeControllergetStatistiquesService', true],
            'App\\Controller\\API\\IngredientApiController::index' => ['privates', '.service_locator.BFCWt9t.App\\Controller\\API\\IngredientApiController::index()', 'getIngredientApiControllerindexService', true],
            'App\\Controller\\API\\PlatApiController::getAllPlats' => ['privates', '.service_locator.9T6YsAE.App\\Controller\\API\\PlatApiController::getAllPlats()', 'getPlatApiControllergetAllPlatsService', true],
            'App\\Controller\\API\\PlatApiController::getPlat' => ['privates', '.service_locator.9T6YsAE.App\\Controller\\API\\PlatApiController::getPlat()', 'getPlatApiControllergetPlatService', true],
            'App\\Controller\\API\\PlatApiController::updatePlat' => ['privates', '.service_locator.9T6YsAE.App\\Controller\\API\\PlatApiController::updatePlat()', 'getPlatApiControllerupdatePlatService', true],
            'App\\Controller\\API\\PlatApiController::addRecetteToPlat' => ['privates', '.service_locator.9T6YsAE.App\\Controller\\API\\PlatApiController::addRecetteToPlat()', 'getPlatApiControlleraddRecetteToPlatService', true],
            'App\\Controller\\API\\PlatApiController::deletePlat' => ['privates', '.service_locator.9T6YsAE.App\\Controller\\API\\PlatApiController::deletePlat()', 'getPlatApiControllerdeletePlatService', true],
            'App\\Controller\\API\\RecetteApiController::getAllRecettes' => ['privates', '.service_locator.nUGD5oq.App\\Controller\\API\\RecetteApiController::getAllRecettes()', 'getRecetteApiControllergetAllRecettesService', true],
            'App\\Controller\\API\\RecetteApiController::getRecette' => ['privates', '.service_locator.nUGD5oq.App\\Controller\\API\\RecetteApiController::getRecette()', 'getRecetteApiControllergetRecetteService', true],
            'App\\Controller\\API\\RecetteApiController::updateRecette' => ['privates', '.service_locator.nUGD5oq.App\\Controller\\API\\RecetteApiController::updateRecette()', 'getRecetteApiControllerupdateRecetteService', true],
            'App\\Controller\\API\\RecetteApiController::deleteRecette' => ['privates', '.service_locator.nUGD5oq.App\\Controller\\API\\RecetteApiController::deleteRecette()', 'getRecetteApiControllerdeleteRecetteService', true],
            'App\\Controller\\API\\StockApiController::show' => ['privates', '.service_locator.KVp9dW1.App\\Controller\\API\\StockApiController::show()', 'getStockApiControllershowService', true],
            'App\\Controller\\API\\StockApiController::update' => ['privates', '.service_locator.KVp9dW1.App\\Controller\\API\\StockApiController::update()', 'getStockApiControllerupdateService', true],
            'App\\Controller\\API\\StockApiController::delete' => ['privates', '.service_locator.KVp9dW1.App\\Controller\\API\\StockApiController::delete()', 'getStockApiControllerdeleteService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\API\\AdminApiController:create' => ['privates', '.service_locator.egipcEH.App\\Controller\\API\\AdminApiController::create()', 'getAdminApiControllercreateService', true],
            'App\\Controller\\API\\AdminApiController:findById' => ['privates', '.service_locator.2ath_dA.App\\Controller\\API\\AdminApiController::findById()', 'getAdminApiControllerfindByIdService', true],
            'App\\Controller\\API\\AdminApiController:findByAll' => ['privates', '.service_locator.2ath_dA.App\\Controller\\API\\AdminApiController::findByAll()', 'getAdminApiControllerfindByAllService', true],
            'App\\Controller\\API\\AdminApiController:login' => ['privates', '.service_locator.6nIdJea.App\\Controller\\API\\AdminApiController::login()', 'getAdminApiControllerloginService', true],
            'App\\Controller\\API\\ClientApiController:create' => ['privates', '.service_locator.egipcEH.App\\Controller\\API\\ClientApiController::create()', 'getClientApiControllercreateService', true],
            'App\\Controller\\API\\ClientApiController:findById' => ['privates', '.service_locator.mjCVlfO.App\\Controller\\API\\ClientApiController::findById()', 'getClientApiControllerfindByIdService', true],
            'App\\Controller\\API\\ClientApiController:findByAll' => ['privates', '.service_locator.mjCVlfO.App\\Controller\\API\\ClientApiController::findByAll()', 'getClientApiControllerfindByAllService', true],
            'App\\Controller\\API\\ClientApiController:listClients' => ['privates', '.service_locator.zroWs1n.App\\Controller\\API\\ClientApiController::listClients()', 'getClientApiControllerlistClientsService', true],
            'App\\Controller\\API\\ClientApiController:login' => ['privates', '.service_locator.qvGhemt.App\\Controller\\API\\ClientApiController::login()', 'getClientApiControllerloginService', true],
            'App\\Controller\\API\\CommandeController:getStatistiques' => ['privates', '.service_locator.75P59IX.App\\Controller\\API\\CommandeController::getStatistiques()', 'getCommandeControllergetStatistiquesService', true],
            'App\\Controller\\API\\IngredientApiController:index' => ['privates', '.service_locator.BFCWt9t.App\\Controller\\API\\IngredientApiController::index()', 'getIngredientApiControllerindexService', true],
            'App\\Controller\\API\\PlatApiController:getAllPlats' => ['privates', '.service_locator.9T6YsAE.App\\Controller\\API\\PlatApiController::getAllPlats()', 'getPlatApiControllergetAllPlatsService', true],
            'App\\Controller\\API\\PlatApiController:getPlat' => ['privates', '.service_locator.9T6YsAE.App\\Controller\\API\\PlatApiController::getPlat()', 'getPlatApiControllergetPlatService', true],
            'App\\Controller\\API\\PlatApiController:updatePlat' => ['privates', '.service_locator.9T6YsAE.App\\Controller\\API\\PlatApiController::updatePlat()', 'getPlatApiControllerupdatePlatService', true],
            'App\\Controller\\API\\PlatApiController:addRecetteToPlat' => ['privates', '.service_locator.9T6YsAE.App\\Controller\\API\\PlatApiController::addRecetteToPlat()', 'getPlatApiControlleraddRecetteToPlatService', true],
            'App\\Controller\\API\\PlatApiController:deletePlat' => ['privates', '.service_locator.9T6YsAE.App\\Controller\\API\\PlatApiController::deletePlat()', 'getPlatApiControllerdeletePlatService', true],
            'App\\Controller\\API\\RecetteApiController:getAllRecettes' => ['privates', '.service_locator.nUGD5oq.App\\Controller\\API\\RecetteApiController::getAllRecettes()', 'getRecetteApiControllergetAllRecettesService', true],
            'App\\Controller\\API\\RecetteApiController:getRecette' => ['privates', '.service_locator.nUGD5oq.App\\Controller\\API\\RecetteApiController::getRecette()', 'getRecetteApiControllergetRecetteService', true],
            'App\\Controller\\API\\RecetteApiController:updateRecette' => ['privates', '.service_locator.nUGD5oq.App\\Controller\\API\\RecetteApiController::updateRecette()', 'getRecetteApiControllerupdateRecetteService', true],
            'App\\Controller\\API\\RecetteApiController:deleteRecette' => ['privates', '.service_locator.nUGD5oq.App\\Controller\\API\\RecetteApiController::deleteRecette()', 'getRecetteApiControllerdeleteRecetteService', true],
            'App\\Controller\\API\\StockApiController:show' => ['privates', '.service_locator.KVp9dW1.App\\Controller\\API\\StockApiController::show()', 'getStockApiControllershowService', true],
            'App\\Controller\\API\\StockApiController:update' => ['privates', '.service_locator.KVp9dW1.App\\Controller\\API\\StockApiController::update()', 'getStockApiControllerupdateService', true],
            'App\\Controller\\API\\StockApiController:delete' => ['privates', '.service_locator.KVp9dW1.App\\Controller\\API\\StockApiController::delete()', 'getStockApiControllerdeleteService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\API\\AdminApiController::create' => '?',
            'App\\Controller\\API\\AdminApiController::findById' => '?',
            'App\\Controller\\API\\AdminApiController::findByAll' => '?',
            'App\\Controller\\API\\AdminApiController::login' => '?',
            'App\\Controller\\API\\ClientApiController::create' => '?',
            'App\\Controller\\API\\ClientApiController::findById' => '?',
            'App\\Controller\\API\\ClientApiController::findByAll' => '?',
            'App\\Controller\\API\\ClientApiController::listClients' => '?',
            'App\\Controller\\API\\ClientApiController::login' => '?',
            'App\\Controller\\API\\CommandeController::getStatistiques' => '?',
            'App\\Controller\\API\\IngredientApiController::index' => '?',
            'App\\Controller\\API\\PlatApiController::getAllPlats' => '?',
            'App\\Controller\\API\\PlatApiController::getPlat' => '?',
            'App\\Controller\\API\\PlatApiController::updatePlat' => '?',
            'App\\Controller\\API\\PlatApiController::addRecetteToPlat' => '?',
            'App\\Controller\\API\\PlatApiController::deletePlat' => '?',
            'App\\Controller\\API\\RecetteApiController::getAllRecettes' => '?',
            'App\\Controller\\API\\RecetteApiController::getRecette' => '?',
            'App\\Controller\\API\\RecetteApiController::updateRecette' => '?',
            'App\\Controller\\API\\RecetteApiController::deleteRecette' => '?',
            'App\\Controller\\API\\StockApiController::show' => '?',
            'App\\Controller\\API\\StockApiController::update' => '?',
            'App\\Controller\\API\\StockApiController::delete' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\API\\AdminApiController:create' => '?',
            'App\\Controller\\API\\AdminApiController:findById' => '?',
            'App\\Controller\\API\\AdminApiController:findByAll' => '?',
            'App\\Controller\\API\\AdminApiController:login' => '?',
            'App\\Controller\\API\\ClientApiController:create' => '?',
            'App\\Controller\\API\\ClientApiController:findById' => '?',
            'App\\Controller\\API\\ClientApiController:findByAll' => '?',
            'App\\Controller\\API\\ClientApiController:listClients' => '?',
            'App\\Controller\\API\\ClientApiController:login' => '?',
            'App\\Controller\\API\\CommandeController:getStatistiques' => '?',
            'App\\Controller\\API\\IngredientApiController:index' => '?',
            'App\\Controller\\API\\PlatApiController:getAllPlats' => '?',
            'App\\Controller\\API\\PlatApiController:getPlat' => '?',
            'App\\Controller\\API\\PlatApiController:updatePlat' => '?',
            'App\\Controller\\API\\PlatApiController:addRecetteToPlat' => '?',
            'App\\Controller\\API\\PlatApiController:deletePlat' => '?',
            'App\\Controller\\API\\RecetteApiController:getAllRecettes' => '?',
            'App\\Controller\\API\\RecetteApiController:getRecette' => '?',
            'App\\Controller\\API\\RecetteApiController:updateRecette' => '?',
            'App\\Controller\\API\\RecetteApiController:deleteRecette' => '?',
            'App\\Controller\\API\\StockApiController:show' => '?',
            'App\\Controller\\API\\StockApiController:update' => '?',
            'App\\Controller\\API\\StockApiController:delete' => '?',
        ]);
    }
}
