<?php

namespace Container4dDYsSm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminApiControllerfindByIdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2ath_dA.App\Controller\API\AdminApiController::findById()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2ath_dA.App\\Controller\\API\\AdminApiController::findById()'] = ($container->privates['.service_locator.2ath_dA'] ?? $container->load('get_ServiceLocator_2athDAService'))->withContext('App\\Controller\\API\\AdminApiController::findById()', $container);
    }
}
