<?php

namespace Container4dDYsSm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClientApiControllerloginService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qvGhemt.App\Controller\API\ClientApiController::login()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qvGhemt.App\\Controller\\API\\ClientApiController::login()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', 'App\\Repository\\ClientRepository', 'getClientRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'repository' => 'App\\Repository\\ClientRepository',
            'em' => '?',
        ]))->withContext('App\\Controller\\API\\ClientApiController::login()', $container);
    }
}
