<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Recette extends \App\Entity\Recette implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'idPlat' => [parent::class, 'idPlat', null],
        "\0".parent::class."\0".'idVilany' => [parent::class, 'idVilany', null],
        "\0".parent::class."\0".'plat' => [parent::class, 'plat', null],
        "\0".parent::class."\0".'relationIngredientRecettes' => [parent::class, 'relationIngredientRecettes', null],
        "\0".parent::class."\0".'temps' => [parent::class, 'temps', null],
        'id' => [parent::class, 'id', null],
        'idPlat' => [parent::class, 'idPlat', null],
        'idVilany' => [parent::class, 'idVilany', null],
        'plat' => [parent::class, 'plat', null],
        'relationIngredientRecettes' => [parent::class, 'relationIngredientRecettes', null],
        'temps' => [parent::class, 'temps', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
