# config/routes.yaml

controllers:
    resource: '../src/Controller/'
    type: attribute   # Utilisation des attributs dans les contrôleurs

api:
    resource: '../src/Controller/API'
    type: attribute      # Utilisation des annotations pour le namespace API
api_admin_login:
  path: /api/admins/login
  controller: App\Controller\API\AdminController::login
  methods: [POST]