# config/routes.yaml

controllers:
    resource: '../src/Controller/'
    type: attribute   # Utilisation des attributs dans les contrôleurs

api:
    resource: '../src/Controller/API'
    type: attribute      # Utilisation des annotations pour le namespace API
